language: cpp

matrix:
  include:
    - os: linux
      compiler:
      - clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang

    - os: linux
      compiler:
      - gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8

    - os: linux
      compiler:
      - gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
  
    - os: osx
      osx_image: xcode11.4
      compiler:
      - clang

    - os: osx
      osx_image: xcode12.3
      compiler:
      - clang

    - os: osx
      osx_image: xcode11.4
      compiler:
      - gcc

    - os: osx
      osx_image: xcode12.3
      compiler:
      - gcc

script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake ..
  - make
  - ctest --output-on-failure
